# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartsupport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='band',
            name='record',
        ),
        migrations.RemoveField(
            model_name='music',
            name='band',
        ),
        migrations.RemoveField(
            model_name='smartsupport',
            name='music',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Smartsupport',
        ),
    ]
